#define SPACE " "
#define SLASH "/"
#define COLON ":"
#define NEWLINE "\n"
#define UNDERSCORE "_"
#define LIT_CANDLE "^"
#define UNLIT_CANDLE "v"
#define MENORAH_BASE "\n      _-| |-_\n      -------"
#define DASHLINE "------------------"
#define INITIAL_TIMESTAMP "00/00/00 00:00:00"
#define TEST_DAY_MESSAGE "Enter Hanukkah Day to test (1-8):\n"
#define SAY_PRAYERS_MESSAGE "Say Prayers? (1 = Yes, 0 = No)\n"
#define CONTINUING_MESSAGE "Continuing."
#define WAIT_TO_CONTINUE_MESSAGE "The menorah should now be lit following the image.\nPlease reset the arduino to continue to normal operation.\n"
#define DAY "day"
#define ZERO "0"